'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm2
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''NameBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiresNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiresNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DobBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DobBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DobRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DobRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EmailBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AddressBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddressBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadAddressLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CreditCardFrontBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreditCardFrontBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadFrontNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadFrontNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ExpirationDateBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpirationDateBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadExpirDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadExpirDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CreditCardBackBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreditCardBackBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadBackNumLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadBackNumLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UsernameBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UsernameBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadUsernameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadUsernameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordsErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordsErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ConfirmPasswordBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPasswordBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CreateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateButton As Global.System.Web.UI.WebControls.Button
End Class
