'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class test_addOrder
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ShapeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShapeDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ColorDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColorDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''WidgetDisplay_Cube control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WidgetDisplay_Cube As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''WidgetDisplay_Sphere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WidgetDisplay_Sphere As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''QuantBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuantBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BadQuantityFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadQuantityFlag As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UnitPriceBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitPriceBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PriceSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PriceSubtotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AddToCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToCart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SubmitOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BadSubmitOrderFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BadSubmitOrderFlag As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShapesListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShapesListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ColorsListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColorsListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''QuantityListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuantityListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''UnitPriceListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitPriceListBox As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''Subtotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Subtotals As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''CurrentTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ComboKeyStorage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboKeyStorage As Global.System.Web.UI.WebControls.ListBox
End Class
